name: Sample
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sample:
    name: Sample
    runs-on: ubuntu-latest
    steps:
      # for checkout Sample Data
      - name: check out
        uses: actions/checkout@v4

      # for tool-path
      - name: Example -toolPath
        id: toolpath
        uses: hanachiru/DotnetToolInspector@main
        with:
          package-id: dotnet-t4
          command-name: t4
          tool-path: ./Tests/Data/tool-path

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.toolpath.outputs.framework-version-major-minor }}

      # for local
      # NOTE: If -local is used, 'dotnet tool restore' must be performed beforehand.
      - name: dotnet tool restore
        working-directory: ./Tests/Data/local
        run: |
          dotnet tool restore
      - name: Example -local
        uses: hanachiru/DotnetToolInspector@main
        with:
          package-id: dotnet-t4
          command-name: t4
          working-directory: ./Tests/Data/local

      # for global
      - name: dotnet tool install
        run: |
          dotnet tool install dotnet-t4 --global
      - name: Example -global
        uses: hanachiru/DotnetToolInspector@main
        with:
          package-id: dotnet-t4
          command-name: t4
          global: true
